server:
  port: 8080

spring:
  datasource:
    name:
    url: jdbc:mysql://localhost:3306/xiaomaibu?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    connect-timeout: 1800
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 8
        max-wait: 1000
  servlet:
    multipart:
      max-file-size: 100MB




mybatis:
  mapper-locations: classpath:mapper/*.xml
